pipeline {
    agent any
   
   
    tools {
       jdk 'jdk8'
        maven 'Maven 3.3.9'
        
    }
    
    stages {

        stage ('Build') {
           
           sh 'mvn package'
       
        }
       
       stage ('Testing') {
           
           sh 'java -cp .:/usr/share/java/junit.jar org.junit.runner.JUnitCore jenkins_demo/src/test/java/hudson/plugins/robot/graph/RobotGraphHelperTest.java ' 
       
        }
    }
}
