pipeline {
    agent any

    stages {
        // stage('Build') {
        //     steps {
        //         // Well, it's python...
        //     }
        // }
        stage('Test') {
            steps {
                echo 'Testing..'
                sh 'git clone https://github.com/Polytech-DevOps-Course-2017/docker_demo.git'
                sh 'cd docker_demo; python3 -m unittest -v'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}

