pipeline {
    agent any

    stages {
        // stage('Build') {
        //     steps {
        //         // Well, it's python...
        //     }
        // }
        stage('Test') {
            steps {
                echo 'Testing..'
                sh '''
if [ -d docker_demo ]; then
    rm -rf jenkins_demo
fi

git clone https://github.com/qezz/jenkins_demo.git

cd mishin.sergey/meaningless-app/

/root/.cargo/bin/cargo clean
/root/.cargo/bin/cargo test -v
'''
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
                echo 'TODO:'
                echo '  Generate docs'
            }
        }
    }
}

